controller:
  config:
    server-tokens: "false"
  service:
    loadBalancerIP: 35.187.162.222
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50

rbac:
  create: true
  serviceAccountName: default
