# List namespaces to create
namespaces:
  - team1
  - team2

# Whether create a default deny-all policy and allow access to kube-dns
networkPolicy:
  create: true

# Assign user and serviceAccounts as cluster-admins
clusterAdmins:
  create: true
  users:
    - projectowner@dev-demo-project-4d6725.iam.gserviceaccount.com

# List roles to limit things you can view / modify with the dashboard
# By default, you only get the "view" role
dashboardPermissions:
  create: true
  clusterRoles:
    - view
    - secret-lister
    - cluster-viewer
