# List namespaces to create
# Use 'secure: true' to add deny-all networkpolicy
namespaces:
- name: team1
  secure: false
- name: team2
  secure: true

# Assign user and serviceAccounts as cluster-admins
clusterAdmins:
  create: true
  users:
    - projectowner@dev-demo-project-4d6725.iam.gserviceaccount.com

# List roles to limit things you can view / modify with the dashboard
dashboardPermissions:
  create: true
  clusterRoles:
    - view
    - secret-lister
    - cluster-viewer
    # - cluster-admin
