kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: cluster-viewer
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  - nodes
  verbs:
  - get
  - list
  - watch
---
# Dashboard only has read-only access and list access to secrets
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-lister
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list"]
